#!/bin/sh
set -eu

COMMENT_COUNT=${COMMENT_COUNT:-2000}
COMMENT_ITERATIONS=${COMMENT_ITERATIONS:-5}
COMMENT_WARMUP=${COMMENT_WARMUP:-1}
COMMENT_OUTPUT=${COMMENT_OUTPUT:-perf/results_comment_attachment.csv}

GRAPH_NODES=${GRAPH_NODES:-1000}
GRAPH_EDGES=${GRAPH_EDGES:-2000}
GRAPH_ITERATIONS=${GRAPH_ITERATIONS:-5}
GRAPH_WARMUP=${GRAPH_WARMUP:-1}
GRAPH_MODE=${GRAPH_MODE:-both}
GRAPH_OUTPUT=${GRAPH_OUTPUT:-perf/results_graph_validation.csv}

LAYOUT_NODES=${LAYOUT_NODES:-500}
LAYOUT_EDGES=${LAYOUT_EDGES:-1000}
LAYOUT_ITERATIONS=${LAYOUT_ITERATIONS:-5}
LAYOUT_WARMUP=${LAYOUT_WARMUP:-1}
LAYOUT_ALGORITHM=${LAYOUT_ALGORITHM:-fixed}
LAYOUT_VALIDATE_GRAPH=${LAYOUT_VALIDATE_GRAPH:-false}
LAYOUT_VALIDATE_OPTIONS=${LAYOUT_VALIDATE_OPTIONS:-false}
LAYOUT_OUTPUT=${LAYOUT_OUTPUT:-perf/results_recursive_layout.csv}
LAYOUT_LAYERED_OUTPUT=${LAYOUT_LAYERED_OUTPUT:-perf/results_recursive_layout_layered.csv}

sh scripts/run_perf_comment_attachment.sh "$COMMENT_COUNT" "$COMMENT_ITERATIONS" "$COMMENT_WARMUP" "$COMMENT_OUTPUT"
sh scripts/run_perf_graph_validation.sh "$GRAPH_NODES" "$GRAPH_EDGES" "$GRAPH_ITERATIONS" "$GRAPH_WARMUP" "$GRAPH_MODE" "$GRAPH_OUTPUT"
sh scripts/run_perf_recursive_layout.sh "$LAYOUT_NODES" "$LAYOUT_EDGES" "$LAYOUT_ITERATIONS" "$LAYOUT_WARMUP" "$LAYOUT_ALGORITHM" "$LAYOUT_VALIDATE_GRAPH" "$LAYOUT_VALIDATE_OPTIONS" "$LAYOUT_OUTPUT"
sh scripts/run_perf_layered_layout.sh "$LAYOUT_NODES" "$LAYOUT_EDGES" "$LAYOUT_ITERATIONS" "$LAYOUT_WARMUP" "$LAYOUT_VALIDATE_GRAPH" "$LAYOUT_VALIDATE_OPTIONS" "$LAYOUT_LAYERED_OUTPUT"
