#!/bin/sh
set -eu

COMMENT_COUNT=${COMMENT_COUNT:-2000}
COMMENT_ITERATIONS=${COMMENT_ITERATIONS:-5}
COMMENT_WARMUP=${COMMENT_WARMUP:-1}
COMMENT_OUTPUT=${COMMENT_OUTPUT:-tests/results_comment_attachment.csv}

GRAPH_NODES=${GRAPH_NODES:-1000}
GRAPH_EDGES=${GRAPH_EDGES:-2000}
GRAPH_ITERATIONS=${GRAPH_ITERATIONS:-5}
GRAPH_WARMUP=${GRAPH_WARMUP:-1}
GRAPH_MODE=${GRAPH_MODE:-both}
GRAPH_OUTPUT=${GRAPH_OUTPUT:-tests/results_graph_validation.csv}

LAYOUT_NODES=${LAYOUT_NODES:-500}
LAYOUT_EDGES=${LAYOUT_EDGES:-1000}
LAYOUT_ITERATIONS=${LAYOUT_ITERATIONS:-5}
LAYOUT_WARMUP=${LAYOUT_WARMUP:-1}
LAYOUT_ALGORITHM=${LAYOUT_ALGORITHM:-fixed}
LAYOUT_VALIDATE_GRAPH=${LAYOUT_VALIDATE_GRAPH:-false}
LAYOUT_VALIDATE_OPTIONS=${LAYOUT_VALIDATE_OPTIONS:-false}
LAYOUT_OUTPUT=${LAYOUT_OUTPUT:-tests/results_recursive_layout.csv}
LAYOUT_LAYERED_OUTPUT=${LAYOUT_LAYERED_OUTPUT:-tests/results_recursive_layout_layered.csv}
RECURSIVE_SCENARIO_PROFILE=${RECURSIVE_SCENARIO_PROFILE:-default}
RECURSIVE_SCENARIOS=${RECURSIVE_SCENARIOS:-}
RECURSIVE_SCENARIO_ITERATIONS=${RECURSIVE_SCENARIO_ITERATIONS:-5}
RECURSIVE_SCENARIO_WARMUP=${RECURSIVE_SCENARIO_WARMUP:-1}
RECURSIVE_SCENARIO_OUTPUT=${RECURSIVE_SCENARIO_OUTPUT:-tests/results_recursive_layout_scenarios.csv}

LAYERED_ISSUE_SCENARIOS=${LAYERED_ISSUE_SCENARIOS:-issue_405,issue_603,issue_680,issue_871,issue_905}
LAYERED_ISSUE_ITERATIONS=${LAYERED_ISSUE_ITERATIONS:-20}
LAYERED_ISSUE_WARMUP=${LAYERED_ISSUE_WARMUP:-3}
LAYERED_ISSUE_OUTPUT=${LAYERED_ISSUE_OUTPUT:-tests/results_layered_issue_scenarios.csv}

sh scripts/run_parity_comment_attachment.sh "$COMMENT_COUNT" "$COMMENT_ITERATIONS" "$COMMENT_WARMUP" "$COMMENT_OUTPUT"
sh scripts/run_parity_graph_validation.sh "$GRAPH_NODES" "$GRAPH_EDGES" "$GRAPH_ITERATIONS" "$GRAPH_WARMUP" "$GRAPH_MODE" "$GRAPH_OUTPUT"
sh scripts/run_parity_recursive_layout.sh "$LAYOUT_NODES" "$LAYOUT_EDGES" "$LAYOUT_ITERATIONS" "$LAYOUT_WARMUP" "$LAYOUT_ALGORITHM" "$LAYOUT_VALIDATE_GRAPH" "$LAYOUT_VALIDATE_OPTIONS" "$LAYOUT_OUTPUT"
sh scripts/run_parity_layered_layout.sh "$LAYOUT_NODES" "$LAYOUT_EDGES" "$LAYOUT_ITERATIONS" "$LAYOUT_WARMUP" "$LAYOUT_VALIDATE_GRAPH" "$LAYOUT_VALIDATE_OPTIONS" "$LAYOUT_LAYERED_OUTPUT"
PARITY_RECURSIVE_SCENARIO_PROFILE="$RECURSIVE_SCENARIO_PROFILE" \
  sh scripts/run_parity_recursive_layout_scenarios.sh "$RECURSIVE_SCENARIOS" "$RECURSIVE_SCENARIO_ITERATIONS" "$RECURSIVE_SCENARIO_WARMUP" "$RECURSIVE_SCENARIO_OUTPUT"
sh scripts/run_parity_layered_issue_scenarios.sh "$LAYERED_ISSUE_SCENARIOS" "$LAYERED_ISSUE_ITERATIONS" "$LAYERED_ISSUE_WARMUP" "$LAYERED_ISSUE_OUTPUT"
